### ISSUE TITLE
Open profile in a new window?

### ISSUE THREAD

**Issue by floydj** [jessedobbelaere/alfred-iterm-profiles-workflow#14]
Such an awesome workflow!

Is there a way to configure so that it'll open the profile in a new window rather than as a new tab in an existing window? I need to create windows all the time for server logs, etc that I need separate from my vim windows.

**Comment by jessedobbelaere** [comment]
hi @floydj ! Glad you like it. 

I took a look, if you open the workflow in alfred and you edit the applescript you can change the behaviour here: 

https://github.com/jessedobbelaere/alfred-iterm-profiles-workflow/blob/b6b44e42b1a9c9dff6b4b4fccadcbea1210b6eea/info.plist#L64-L68

Change it to :

```diff
- create tab with profile q
+ create window with profile q
```

Then it should always open the profile as a new window, instead of a tab

**Comment by floydj** [comment]
Many thanks!
